language: cpp
compiler:
  - gcc
  - clang
cache: apt
before_script:
   ./tools/lnx-cibuild.before.sh
script:
  ./tools/lnx-cibuild.sh
env:
  - ENABLE_STYLE_TESTING=On ENABLE_UNITYBUILD=Off WITH_GUI=On
#- ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=On WITH_GUI=On
  - ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=On ACTIVE_TESTS=TOPP
  - ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=On ACTIVE_TESTS=CLASS_TESTS
  - ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=On ACTIVE_TESTS=ALL
  - ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=Off ACTIVE_TESTS=ALL
matrix:
  exclude:
    - env: ENABLE_STYLE_TESTING=On ENABLE_UNITYBUILD=Off WITH_GUI=On
      compiler: clang
#    - env: ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=On WITH_GUI=On
#      compiler: gcc
    - env: ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=On ACTIVE_TESTS=ALL
      compiler: gcc
    - env: ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=On ACTIVE_TESTS=TOPP
      compiler: clang
    - env: ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=On ACTIVE_TESTS=CLASS_TESTS
      compiler: clang
    - env: ENABLE_STYLE_TESTING=Off ENABLE_UNITYBUILD=Off WITH_GUI=Off ACTIVE_TESTS=ALL
      compiler: gcc
